### ISSUE TITLE
Crashes with Fabric Loader 0.16.9 on 1.21.3

### ISSUE THREAD

**Issue by TheOfficialSeri** [Bactrosaurus/bactromod#12]
**Minecraft crashes with only BactroMod `2.6` and Fabric Language Kotlin `1.12.3+kotlin.2.0.21`.
Game version: `1.21.3`
Fabric Loader Version: `0.16.9`**

Game Log: https://mclo.gs/U2pxIGb
```
[11:39:18] [main/INFO]: Loading Minecraft 1.21.3 with Fabric Loader 0.16.9
[11:39:18] [main/INFO]: Loading 19 mods:
	- bactromod 2.6
	- fabric-language-kotlin 1.12.3+kotlin.2.0.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.25.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.9.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.9.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.1
	   |-- org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm 0.5.4
	   |-- org_jetbrains_kotlinx_kotlinx-io-core-jvm 0.5.4
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.7.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.7.3
	- fabricloader 0.16.9
	   \-- mixinextras 0.4.1
	- java 21
	- minecraft 1.21.3
[11:39:18] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/ModrinthApp/meta/libraries/net/fabricmc/sponge-mixin/0.15.4+mixin.0.8.7/sponge-mixin-0.15.4+mixin.0.8.7.jar Service=Knot/Fabric Env=CLIENT
[11:39:18] [main/INFO]: Compatibility level set to JAVA_21
[11:39:20] [Datafixer Bootstrap/INFO]: 237 Datafixer optimizations took 545 milliseconds
[11:39:26] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[11:39:26] [Render thread/INFO]: Setting user: {MINECRAFT_USERNAME}
[11:39:26] [Render thread/INFO]: Initializing BactroMod...
[11:39:26] [Render thread/INFO]: Backend library: LWJGL version 3.3.3-snapshot
[11:39:26] [Render thread/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).

```
Crash log: https://mclo.gs/WtS4Vb5
```
---- Minecraft Crash Report ----
// Don't do that.

Time: 2024-11-03 11:39:30
Description: Initializing game

java.lang.ExceptionInInitializerError
	at knot//net.minecraft.class_8538.method_51643(class_8538.java:22)
	at knot//net.minecraft.class_377.method_2012(class_377.java:186)
	at knot//net.minecraft.class_7191.bake(class_7191.java:54)
	at knot//net.minecraft.class_377.method_57038(class_377.java:73)
	at knot//net.minecraft.class_377.method_57036(class_377.java:62)
	at knot//net.minecraft.class_377.method_2004(class_377.java:57)
	at knot//net.minecraft.class_378.method_27540(class_378.java:67)
	at knot//net.minecraft.class_156.method_654(class_156.java:584)
	at knot//net.minecraft.class_378.<init>(class_378.java:67)
	at knot//net.minecraft.class_310.<init>(class_310.java:576)
	at knot//net.minecraft.client.main.Main.main(Main.java:248)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_329 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at knot//net.minecraft.class_1921.<clinit>(class_1921.java:906)
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 19 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector is(Lnet/minecraft/class_1799;Lnet/minecraft/class_1792;)Z in bactromod.mixins.json:features.nopumpkinblur.MixinGui from mod bactromod failed injection check, (0/1) succeeded. Scanned 0 target(s). Using refmap bactromod-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:531)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1490)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:752)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:330)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 22 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.minecraft.class_8538.method_51643(class_8538.java:22)
	at knot//net.minecraft.class_377.method_2012(class_377.java:186)
	at knot//net.minecraft.class_7191.bake(class_7191.java:54)
	at knot//net.minecraft.class_377.method_57038(class_377.java:73)
	at knot//net.minecraft.class_377.method_57036(class_377.java:62)
	at knot//net.minecraft.class_377.method_2004(class_377.java:57)
	at knot//net.minecraft.class_378.method_27540(class_378.java:67)
	at knot//net.minecraft.class_156.method_654(class_156.java:584)
	at knot//net.minecraft.class_378.<init>(class_378.java:67)
	at knot//net.minecraft.class_310.<init>(class_310.java:576)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Erweiterte Windows 32 Base-API:10.0.22621.4455 (WinBuild.160101.0800):Microsoft Corporation
		AppXDeploymentClient.dll:AppX Deployment Client-DLL:10.0.22621.4455 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:Bibliothek für Steuerelemente:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Krypto-API32:10.0.22621.4455 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation
		CoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.22621.4391 (WinBuild.160101.0800):Microsoft Corporation
		CoreUIComponents.dll:Microsoft Core UI Components Dll:10.0.22621.4391:Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22621.3593 (WinBuild.160101.0800):Microsoft Corporation
		DEVOBJ.dll:Device Information Set DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS-Client-API-DLL:10.0.22621.4455 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22621.4036 (WinBuild.160101.0800):Microsoft Corporation
		GLU32.dll:OpenGL-Hilfsprogrammbibliotheks-DLL:10.0.22621.4455 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP-Hilfs-API:10.0.22621.4455 (WinBuild.160101.0800):Microsoft Corporation
		IntelControlLib.dll:Intel Graphics Control Lib Runtime:1.0.202:
		KERNEL32.DLL:Client-DLL für Windows NT-Basis-API:10.0.22621.4455 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Client-DLL für Windows NT-Basis-API:10.0.22621.4455 (WinBuild.160101.0800):Microsoft Corporation
		MMDevApi.dll:MMDevice-API:10.0.22621.4455 (WinBuild.160101.0800):Microsoft Corporation
		MSCTF.dll:MSCTF-Server-DLL:10.0.22621.4455 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		NetworkExplorer.dll:Netzwerk-Explorer:10.0.22621.4455 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE für Windows:10.0.22621.4455 (WinBuild.160101.0800):Microsoft Corporation
		Oleacc.dll:Active Accessibility Core Component:7.2.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		OpenAL.dll:Main implementation library:1.23.1:
		POWRPROF.dll:Power Profile Helper DLL:10.0.22621.4455 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Unterstützungs-DLL für Leistungsdaten:10.0.22621.4455 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remoteprozeduraufruf-Laufzeitumgebung:10.0.22621.4455 (WinBuild.160101.0800):Microsoft Corporation
		SETUPAPI.dll:Windows Setup-API:10.0.22621.4455 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22621.4455 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Allgemeine Windows-Shell-DLL:10.0.22621.4455 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Client-DLL für Windows USER-API (mehrere Benutzer):10.0.22621.4455 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22621.4455 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.31.31103.0:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP-Dienste:10.0.22621.4455 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API-DLL:10.0.22621.4455 (WinBuild.160101.0800):Microsoft Corporation
		WINSTA.dll:Winstation Library:10.0.22621.4391 (WinBuild.160101.0800):Microsoft Corporation
		WINTRUST.dll:Microsoft Trust Verification APIs:10.0.22621.4391 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0-32-Bit-DLL:10.0.22621.4455 (WinBuild.160101.0800):Microsoft Corporation
		WTSAPI32.dll:Windows Remote Desktop Session Host Server SDK APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		Windows.ApplicationModel.dll:Windows-ApplicationModel-API-Server:10.0.22621.4455 (WinBuild.160101.0800):Microsoft Corporation
		Windows.FileExplorer.Common.dll:Windows.FileExplorer.Common:10.0.22621.4455 (WinBuild.160101.0800):Microsoft Corporation
		Windows.StateRepositoryPS.dll:Windows StateRepository Proxy/Stub Server:10.0.22621.4036 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation
		antimalware_provider64.dll:AMSI provider
```
Modrinth profile (`.mrpack` isn't supported on GitHub, just remove the `.txt`): [test 1.0.0.mrpack.txt](https://github.com/user-attachments/files/17610097/test.1.0.0.mrpack.txt)

**Comment by Bactrosaurus** [comment]
Sorry about that. Really dumb mistake on my side! Should be fixed in newly uploaded version on Modrinth!
